# Generated by Django 2.2.3 on 2019-07-18 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False, verbose_name='sequence number')),
                ('label_name', models.CharField(max_length=10, verbose_name='class label')),
            ],
            options={
                'verbose_name': 'song classify',
                'verbose_name_plural': 'song classifies',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False, verbose_name='sequence number')),
                ('song_name', models.CharField(max_length=50, verbose_name='song name')),
                ('song_singer', models.CharField(max_length=50, verbose_name='player')),
                ('song_time', models.CharField(max_length=10, verbose_name='duration')),
                ('song_album', models.CharField(max_length=50, verbose_name='album')),
                ('song_languages', models.CharField(max_length=20, verbose_name='language')),
                ('song_type', models.CharField(max_length=20, verbose_name='type')),
                ('song_release', models.CharField(max_length=20, verbose_name='issue time')),
                ('song_image', models.CharField(max_length=20, verbose_name='song image')),
                ('song_lyrics', models.CharField(default='no lyrics now', max_length=50, verbose_name='lyrics')),
                ('song_file', models.CharField(max_length=50, verbose_name='song file')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Label', verbose_name='song name classify')),
            ],
            options={
                'verbose_name': 'song info',
                'verbose_name_plural': 'song infos',
            },
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('dynamic_id', models.AutoField(primary_key=True, serialize=False, verbose_name='sequence number')),
                ('dynamic_plays', models.IntegerField(verbose_name='play times')),
                ('dynamic_search', models.IntegerField(verbose_name='search times')),
                ('dynamic_down', models.IntegerField(verbose_name='download times')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Song', verbose_name='song name')),
            ],
            options={
                'verbose_name': 'song dynamic',
                'verbose_name_plural': 'song dynamics',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='sequence number')),
                ('comment_text', models.CharField(max_length=500, verbose_name='content')),
                ('comment_user', models.CharField(max_length=20, verbose_name='user')),
                ('comment_date', models.CharField(max_length=50, verbose_name='date')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Song', verbose_name='song name')),
            ],
            options={
                'verbose_name': 'song comment',
                'verbose_name_plural': 'song comments',
            },
        ),
    ]
