# Generated by Django 2.2.3 on 2019-07-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190718_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_image',
            new_name='song_img',
        ),
    ]
